### PR TITLE
added license moved recipe into repo

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@muryanto1 not positive why coverage dropped suddenly?

**Comment by muryanto1** [comment]
Charles,
can you look at the output of these 2 test logs?
When coverage was at 80%:  https://circleci.com/gh/CDAT/thermo/132
When coverage dropped to 66.8%:  (new_license branch): https://circleci.com/gh/CDAT/thermo/136

It looks like in the run with new_license branch is missing running one of the tests.

**Comment by doutriaux1** [comment]
@muryanto1 I switched to setupttols the coverage should now appear on the PR (finger crossed). Will take a look when the results are in.

**Comment by doutriaux1** [comment]
@muryanto1 looks like I broke coverage... Can you please double check my edits on circleci/config. Thx.

**Comment by muryanto1** [comment]
Changes to .circleci/config.yml looks ok now.

**Comment by doutriaux1** [comment]
@muryanto1 with my newer testsrunner it passes on py3.

**Comment by doutriaux1** [comment]
```
b'Name                               Stmts   Miss  Cover   Missing'
b'----------------------------------------------------------------'
b'lib/thermo.py                        876    175    80%   91-123, 125-145, 158, 163, 176, 191, 241-250, 260-261, 268, 287-291, 303-309, 314, 415-443, 495-500, 568-572, 580, 583-584, 592, 595-599, 607, 610, 618, 621-622, 633-634, 645-646, 657-658, 669-670, 681-682, 693-694, 705-706, 728, 731, 744-745, 789, 791-792, 934-936, 941, 943, 992-999, 1026-1027, 1159-1169, 1202'
b'tests/basetest.py                     49      6    88%   11, 17-18, 21-22, 37'
b'tests/checkimage.py                  107     38    64%   26-29, 40-42, 51, 58-59, 64, 78, 92, 95-96, 99-101, 110-125, 128-135, 138'
b'tests/test_thermo_basic.py            54      0   100%'
b'tests/test_thermo_no_coredump.py      31      3    90%   17, 23-24'
b'----------------------------------------------------------------'
b'TOTAL                               1117    222    80%'
```

**Review by muryanto1 — APPROVED** [review]

**Comment by muryanto1** [comment]
I ran it locally with coverage on, and tests passed with 80% coverage.  good to merge.

**Pull request merged**
